### ISSUE TITLE
Tool name

### ISSUE THREAD

**Issue by leclairm** [C2SM/Sirocco#15]
We need to think about a new name because WCFlow is too toilets oriented :smile: (no go from the hierarchy!) ... I have a few things in mind.
- I thought about a character of the Aïda opera. The easiest to pronounce is "Radames".
- Because it's a layer on top of AiiDA, we could use "Pacha", because the opera was ordered by Ismaïl Pacha, the Egypt Pacha at the time.

I'm currently leaning towards "Pacha"

For the command line, we could use verdi subcomands: `verdi reherse` for generating the preview and `verdi orchestrate`  for launching the workflow.

**Comment by leclairm** [comment]
> I think ethiopia is too close to the country name that everyone will mispell it when importing.

What do you mean by too close? It's just the country name.

**Comment by GeigerJ2** [comment]
With @agoscinski on this topic, also liked `PACHA`. `CFLOW` and `CLIFF` are also taken😅 https://pypi.org/project/cflow/
https://pypi.org/project/cliff/

`CWFLOW` as available, though.

**Comment by leclairm** [comment]
As @DropD mentionned, I'd be fine not pretending it's an Acronym but I still like
- the integration in the AiiDA story
- that it starts with ETH
We could even spell it ETHiopiiA to reflect these points.

**Comment by leclairm** [comment]
@agoscinski @GeigerJ2 @DropD 
Would you be fine to rename the tool to ETHiopiiA once for all? I'd mention the "acronym" in a sentence like "if you really like acronyms, could stand for ... "

**Comment by agoscinski** [comment]
I will highly dislike typing it as command line tool and as python import. I think the writing is also not so clear from the pronunciation so many people will mistype it from hearing the name. How it is derived from the name looks a bit ridiculous, but this we never have to expose to the public. I am much more a fan of something shorter, simpler like `ethope`, `athope`, `etope`, `atope` (a bit like biotope).

**Comment by agoscinski** [comment]
And if you don't like my shorter suggestion here some chatgpt suggetions which don't sound bad
> Zephyros – Named after the Greek god of the west wind, symbolizing the dynamic nature of weather and climate processes.
StratoFlow – Inspired by the stratosphere, evoking layers of atmosphere and data flow.
NimbusCore – "Nimbus" refers to clouds, suggesting weather, while "Core" implies a solid, central processing engine.
Tempestia – Suggests powerful, dynamic weather systems (tempests), alongside seamless orchestration.
HorizonLoop – Implies the broad view of climate processes, with the "loop" referencing automated workflows.
CirrusEngine – Named after high-altitude clouds, signaling light, agile workflows for atmospheric modeling.
Fluxterra – Combining "flux" (the flow of data) with "terra" (Earth), highlighting the planetary and dynamic nature of the project.
AerisForge – "Aeris" means air, and "Forge" suggests the crafting or creation of workflows.
CycloneOps – Evokes powerful natural systems like cyclones while referencing the operational and automated nature of the workflows.
SolsticeFlow – "Solstice" marks significant points in the Earth's climate, symbolizing change and cycles, tied with seamless workflow handling.

and abbreviated

> Zephyr
Strato
Nimbus
Tempest
Horizon
Cirrus
Flux
Aeris
Cyclo
Solis

**Comment by agoscinski** [comment]
Sure we can do a 0.0.0-dev release. Just wait @DropD response

**Comment by leclairm** [comment]
There's even an easy logo, which is the name in egyptian Arabic: خمسين

**Comment by leclairm** [comment]
Sirocco is now on pypi.
