### ISSUE TITLE
Add example config

### ISSUE THREAD

**Issue by agoscinski** [C2SM/Sirocco#21]
With we use the examples in the tests which is fine for the moment, but we should keep the two folders separate at some point

**Comment by leclairm** [comment]
@agoscinski I'm not sure I see what you meant by that. Is that still a thing?

**Comment by agoscinski** [comment]
At some point we used the examples configs in the test. This is not anymore the case. Actually now there is no example config which also should be fixed

**Comment by agoscinski** [comment]
The PR that uses the examples in the tests has not been merged. I will just use the new config files that have been added to the tests and don't use the example.
