### ISSUE TITLE
Differentiate between actual dependencies and other submission conditions

### ISSUE THREAD

**Issue by GeigerJ2** [C2SM/Sirocco#5]
EDIT: Actually, I just realized that currently, "depends" *only* specifies such optional dependencies, while actual, strict dependencies are defined by the input / output file relations for the different tasks.

In the YAML file, we want to specify certain dependencies, e.g. `ICON` starting from the previous `restart` file, and from the input file that comes from `preproc`. These are actual, strict dependencies.

In addition, there should be certain additional restrictions, e.g. `preproc` for a cycle / step should be started when the *grandparent* `ICON` run has finished. However, `preproc` does not *actually depend* on `ICON`. Rather, this is more a safeguard to avoid all `preproc` processes being submitted at once, as they are all fully independent. To differentiate such a restriction from actual dependencies as described above, @agoscinski and I propose to replace the `depends` keyword with `submit_after` for these cases in the current YAML spec. For the visualization, these can still be treated exactly the same, but they will be handled very differently by the AiiDA-powered runner.

**Comment by agoscinski** [comment]
In aiida we use the "wait_on" for this functionality. Would this be ok? `wait` or `wait_on`

**Comment by leclairm** [comment]
> In aiida we use the term `wait_on` for this functionality. Would this be ok? `wait` or `wait_on`

Yes, all good

**Comment by agoscinski** [comment]
Keeping issue open until this is implemented and merged in main
